spring.application.name=transporte
# Conexión a Neon.tech (PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-patient-snow-axol5i77-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_5uYsGTl7RBUc
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA (Hibernate)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true